
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "BaselineProfileSupport", isSet = false )
    public class BaselineProfileSupport implements IASN1PreparedElement {
            
        @ASN1Element ( name = "baseline-revision", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private BaselineRevision baseline_revision = null;
                
  
        @ASN1Element ( name = "max-mtu-rx", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 max_mtu_rx = null;
                
  
        @ASN1Element ( name = "max-mtu-tx", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 max_mtu_tx = null;
                
  
        @ASN1Element ( name = "max-bw-tx", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 max_bw_tx = null;
                
  
        @ASN1Element ( name = "max-mds-hierarchy", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 max_mds_hierarchy = null;
                
  
        @ASN1Element ( name = "options", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private BaselineOptions options = null;
                
  
        @ASN1Element ( name = "optional-packages", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AttributeList optional_packages = null;
                
  
        
        public BaselineRevision getBaseline_revision () {
            return this.baseline_revision;
        }

        

        public void setBaseline_revision (BaselineRevision value) {
            this.baseline_revision = value;
        }
        
  
        
        public INT_U32 getMax_mtu_rx () {
            return this.max_mtu_rx;
        }

        

        public void setMax_mtu_rx (INT_U32 value) {
            this.max_mtu_rx = value;
        }
        
  
        
        public INT_U32 getMax_mtu_tx () {
            return this.max_mtu_tx;
        }

        

        public void setMax_mtu_tx (INT_U32 value) {
            this.max_mtu_tx = value;
        }
        
  
        
        public INT_U32 getMax_bw_tx () {
            return this.max_bw_tx;
        }

        

        public void setMax_bw_tx (INT_U32 value) {
            this.max_bw_tx = value;
        }
        
  
        
        public INT_U16 getMax_mds_hierarchy () {
            return this.max_mds_hierarchy;
        }

        

        public void setMax_mds_hierarchy (INT_U16 value) {
            this.max_mds_hierarchy = value;
        }
        
  
        
        public BaselineOptions getOptions () {
            return this.options;
        }

        

        public void setOptions (BaselineOptions value) {
            this.options = value;
        }
        
  
        
        public AttributeList getOptional_packages () {
            return this.optional_packages;
        }

        

        public void setOptional_packages (AttributeList value) {
            this.optional_packages = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(BaselineProfileSupport.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            