
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_StringSpec", isSet = false )
    public class Poc_StringSpec implements IASN1PreparedElement {
            
        @ASN1Element ( name = "str-max-len", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 str_max_len = null;
                
  
        @ASN1Element ( name = "str-flags", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_StringFlags str_flags = null;
                
  
        
        public INT_U16 getStr_max_len () {
            return this.str_max_len;
        }

        

        public void setStr_max_len (INT_U16 value) {
            this.str_max_len = value;
        }
        
  
        
        public Poc_StringFlags getStr_flags () {
            return this.str_flags;
        }

        

        public void setStr_flags (Poc_StringFlags value) {
            this.str_flags = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_StringSpec.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            