
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_ExtTimeStamp", isSet = false )
    public class Poc_ExtTimeStamp implements IASN1PreparedElement {
            
        @ASN1Element ( name = "time-stamp-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_TimeStampId time_stamp_id = null;
                
  @ASN1Any( name = "" )
    
        @ASN1Element ( name = "time-stamp", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] time_stamp = null;
                
  
        
        public Poc_TimeStampId getTime_stamp_id () {
            return this.time_stamp_id;
        }

        

        public void setTime_stamp_id (Poc_TimeStampId value) {
            this.time_stamp_id = value;
        }
        
  
        
        public byte[] getTime_stamp () {
            return this.time_stamp;
        }

        

        public void setTime_stamp (byte[] value) {
            this.time_stamp = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_ExtTimeStamp.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            