
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_EnumMsmtRangeLabel", isSet = false )
    public class Poc_EnumMsmtRangeLabel implements IASN1PreparedElement {
            
        @ASN1Element ( name = "value", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_EnumVal value = null;
                
  @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "label", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] label = null;
                
  
        
        public Poc_EnumVal getValue () {
            return this.value;
        }

        

        public void setValue (Poc_EnumVal value) {
            this.value = value;
        }
        
  
        
        public byte[] getLabel () {
            return this.label;
        }

        

        public void setLabel (byte[] value) {
            this.label = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_EnumMsmtRangeLabel.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            