
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_RORJapdu", isSet = false )
    public class Poc_RORJapdu implements IASN1PreparedElement {
            
        @ASN1Element ( name = "invokeID", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private InvokeIDType invokeID = null;
                
  
        @ASN1Element ( name = "problem", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_Problem problem = null;
                
  
        
        public InvokeIDType getInvokeID () {
            return this.invokeID;
        }

        

        public void setInvokeID (InvokeIDType value) {
            this.invokeID = value;
        }
        
  
        
        public Poc_Problem getProblem () {
            return this.problem;
        }

        

        public void setProblem (Poc_Problem value) {
            this.problem = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_RORJapdu.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            