
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_ScaledRange16", isSet = false )
    public class Poc_ScaledRange16 implements IASN1PreparedElement {
            
        @ASN1Element ( name = "lower-scaled-value", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 lower_scaled_value = null;
                
  
        @ASN1Element ( name = "upper-scaled-value", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 upper_scaled_value = null;
                
  
        
        public INT_U16 getLower_scaled_value () {
            return this.lower_scaled_value;
        }

        

        public void setLower_scaled_value (INT_U16 value) {
            this.lower_scaled_value = value;
        }
        
  
        
        public INT_U16 getUpper_scaled_value () {
            return this.upper_scaled_value;
        }

        

        public void setUpper_scaled_value (INT_U16 value) {
            this.upper_scaled_value = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_ScaledRange16.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            