
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_CmplxElemInfo", isSet = false )
    public class Poc_CmplxElemInfo implements IASN1PreparedElement {
            
        @ASN1Element ( name = "class-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type class_id = null;
                
  
        @ASN1Element ( name = "max-inst", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 max_inst = null;
                
  
        @ASN1Element ( name = "max-inst-comp", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 max_inst_comp = null;
                
  
        @ASN1Element ( name = "max-comp-no", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 max_comp_no = null;
                
  
        @ASN1Element ( name = "max-inst-mplex", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 max_inst_mplex = null;
                
  
        @ASN1Element ( name = "max-str-size", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 max_str_size = null;
                
  
        
        public OID_Type getClass_id () {
            return this.class_id;
        }

        

        public void setClass_id (OID_Type value) {
            this.class_id = value;
        }
        
  
        
        public INT_U8 getMax_inst () {
            return this.max_inst;
        }

        

        public void setMax_inst (INT_U8 value) {
            this.max_inst = value;
        }
        
  
        
        public INT_U8 getMax_inst_comp () {
            return this.max_inst_comp;
        }

        

        public void setMax_inst_comp (INT_U8 value) {
            this.max_inst_comp = value;
        }
        
  
        
        public INT_U8 getMax_comp_no () {
            return this.max_comp_no;
        }

        

        public void setMax_comp_no (INT_U8 value) {
            this.max_comp_no = value;
        }
        
  
        
        public INT_U8 getMax_inst_mplex () {
            return this.max_inst_mplex;
        }

        

        public void setMax_inst_mplex (INT_U8 value) {
            this.max_inst_mplex = value;
        }
        
  
        
        public INT_U16 getMax_str_size () {
            return this.max_str_size;
        }

        

        public void setMax_str_size (INT_U16 value) {
            this.max_str_size = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_CmplxElemInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            