
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_SaObsValue", isSet = false )
    public class Poc_SaObsValue implements IASN1PreparedElement {
            
        @ASN1Element ( name = "metric-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type metric_id = null;
                
  
        @ASN1Element ( name = "state", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MeasurementStatus state = null;
                
  @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "array", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] array = null;
                
  
        
        public OID_Type getMetric_id () {
            return this.metric_id;
        }

        

        public void setMetric_id (OID_Type value) {
            this.metric_id = value;
        }
        
  
        
        public MeasurementStatus getState () {
            return this.state;
        }

        

        public void setState (MeasurementStatus value) {
            this.state = value;
        }
        
  
        
        public byte[] getArray () {
            return this.array;
        }

        

        public void setArray (byte[] value) {
            this.array = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_SaObsValue.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            