
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_CmplxObsElem", isSet = false )
    public class Poc_CmplxObsElem implements IASN1PreparedElement {
            
        @ASN1Element ( name = "cm-elem-idx", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 cm_elem_idx = null;
                
  
        @ASN1Element ( name = "cm-obs-elem-flgs", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_CmplxObsElemFlags cm_obs_elem_flgs = null;
                
  
        @ASN1Element ( name = "attributes", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AttributeList attributes = null;
                
  
        
        public INT_U8 getCm_elem_idx () {
            return this.cm_elem_idx;
        }

        

        public void setCm_elem_idx (INT_U8 value) {
            this.cm_elem_idx = value;
        }
        
  
        
        public Poc_CmplxObsElemFlags getCm_obs_elem_flgs () {
            return this.cm_obs_elem_flgs;
        }

        

        public void setCm_obs_elem_flgs (Poc_CmplxObsElemFlags value) {
            this.cm_obs_elem_flgs = value;
        }
        
  
        
        public AttributeList getAttributes () {
            return this.attributes;
        }

        

        public void setAttributes (AttributeList value) {
            this.attributes = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_CmplxObsElem.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            