
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_PollProfileSupport", isSet = false )
    public class Poc_PollProfileSupport implements IASN1PreparedElement {
            
        @ASN1Element ( name = "poll-profile-revision", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_PollProfileRevision poll_profile_revision = null;
                
  
        @ASN1Element ( name = "min-poll-period", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RelativeTime min_poll_period = null;
                
  
        @ASN1Element ( name = "max-mtu-rx", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 max_mtu_rx = null;
                
  
        @ASN1Element ( name = "max-mtu-tx", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 max_mtu_tx = null;
                
  
        @ASN1Element ( name = "max-bw-tx", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 max_bw_tx = null;
                
  
        @ASN1Element ( name = "options", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_PollProfileOptions options = null;
                
  
        @ASN1Element ( name = "optional-packages", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AttributeList optional_packages = null;
                
  
        
        public Poc_PollProfileRevision getPoll_profile_revision () {
            return this.poll_profile_revision;
        }

        

        public void setPoll_profile_revision (Poc_PollProfileRevision value) {
            this.poll_profile_revision = value;
        }
        
  
        
        public RelativeTime getMin_poll_period () {
            return this.min_poll_period;
        }

        

        public void setMin_poll_period (RelativeTime value) {
            this.min_poll_period = value;
        }
        
  
        
        public INT_U32 getMax_mtu_rx () {
            return this.max_mtu_rx;
        }

        

        public void setMax_mtu_rx (INT_U32 value) {
            this.max_mtu_rx = value;
        }
        
  
        
        public INT_U32 getMax_mtu_tx () {
            return this.max_mtu_tx;
        }

        

        public void setMax_mtu_tx (INT_U32 value) {
            this.max_mtu_tx = value;
        }
        
  
        
        public INT_U32 getMax_bw_tx () {
            return this.max_bw_tx;
        }

        

        public void setMax_bw_tx (INT_U32 value) {
            this.max_bw_tx = value;
        }
        
  
        
        public Poc_PollProfileOptions getOptions () {
            return this.options;
        }

        

        public void setOptions (Poc_PollProfileOptions value) {
            this.options = value;
        }
        
  
        
        public AttributeList getOptional_packages () {
            return this.optional_packages;
        }

        

        public void setOptional_packages (AttributeList value) {
            this.optional_packages = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_PollProfileSupport.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            