
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_EventReportResult", isSet = false )
    public class Poc_EventReportResult implements IASN1PreparedElement {
            
        @ASN1Element ( name = "managedObject", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_ManagedObjectId managedObject = null;
                
  
        @ASN1Element ( name = "currentTime", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RelativeTime currentTime = null;
                
  
        @ASN1Element ( name = "eventType", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type eventType = null;
                
  @ASN1Any( name = "" )
    
        @ASN1Element ( name = "eventReplyInfo", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] eventReplyInfo = null;
                
  
        
        public Poc_ManagedObjectId getManagedObject () {
            return this.managedObject;
        }

        

        public void setManagedObject (Poc_ManagedObjectId value) {
            this.managedObject = value;
        }
        
  
        
        public RelativeTime getCurrentTime () {
            return this.currentTime;
        }

        

        public void setCurrentTime (RelativeTime value) {
            this.currentTime = value;
        }
        
  
        
        public OID_Type getEventType () {
            return this.eventType;
        }

        

        public void setEventType (OID_Type value) {
            this.eventType = value;
        }
        
  
        
        public byte[] getEventReplyInfo () {
            return this.eventReplyInfo;
        }

        

        public void setEventReplyInfo (byte[] value) {
            this.eventReplyInfo = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_EventReportResult.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            