
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_MibDataEntry", isSet = false )
    public class Poc_MibDataEntry implements IASN1PreparedElement {
            
        @ASN1Element ( name = "mib-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_CC_Oid mib_id = null;
                
  
        @ASN1Element ( name = "mib-attributes", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AttributeList mib_attributes = null;
                
  
        
        public Poc_CC_Oid getMib_id () {
            return this.mib_id;
        }

        

        public void setMib_id (Poc_CC_Oid value) {
            this.mib_id = value;
        }
        
  
        
        public AttributeList getMib_attributes () {
            return this.mib_attributes;
        }

        

        public void setMib_attributes (AttributeList value) {
            this.mib_attributes = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_MibDataEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            