
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_ScoOperInvokeError", isSet = false )
    public class Poc_ScoOperInvokeError implements IASN1PreparedElement {
            
        @ASN1Element ( name = "invoke-cookie", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 invoke_cookie = null;
                
  @ASN1Integer( name = "" )
    
        @ASN1Element ( name = "op-error", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Long op_error = null;
                
  
@ASN1SequenceOf( name = "failed-operation-list", isSetOf = false ) 

    
        @ASN1Element ( name = "failed-operation-list", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private java.util.Collection<InstNumber>  failed_operation_list = null;
                
  
        
        public INT_U32 getInvoke_cookie () {
            return this.invoke_cookie;
        }

        

        public void setInvoke_cookie (INT_U32 value) {
            this.invoke_cookie = value;
        }
        
  
        
        public Long getOp_error () {
            return this.op_error;
        }

        

        public void setOp_error (Long value) {
            this.op_error = value;
        }
        
  
        
        public java.util.Collection<InstNumber>  getFailed_operation_list () {
            return this.failed_operation_list;
        }

        

        public void setFailed_operation_list (java.util.Collection<InstNumber>  value) {
            this.failed_operation_list = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_ScoOperInvokeError.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            