
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_RangeOpText", isSet = false )
    public class Poc_RangeOpText implements IASN1PreparedElement {
            @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "low-text", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] low_text = null;
                
  @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "high-text", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] high_text = null;
                
  
        
        public byte[] getLow_text () {
            return this.low_text;
        }

        

        public void setLow_text (byte[] value) {
            this.low_text = value;
        }
        
  
        
        public byte[] getHigh_text () {
            return this.high_text;
        }

        

        public void setHigh_text (byte[] value) {
            this.high_text = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_RangeOpText.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            