
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_AlertOpTextString", isSet = false )
    public class Poc_AlertOpTextString implements IASN1PreparedElement {
            @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "lower-text", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] lower_text = null;
                
  @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "upper-text", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] upper_text = null;
                
  
        
        public byte[] getLower_text () {
            return this.lower_text;
        }

        

        public void setLower_text (byte[] value) {
            this.lower_text = value;
        }
        
  
        
        public byte[] getUpper_text () {
            return this.upper_text;
        }

        

        public void setUpper_text (byte[] value) {
            this.upper_text = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_AlertOpTextString.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            