
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_CmplxMetricInfo", isSet = false )
    public class Poc_CmplxMetricInfo implements IASN1PreparedElement {
            
        @ASN1Element ( name = "max-mplex-obs", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 max_mplex_obs = null;
                
  
        @ASN1Element ( name = "max-mplex-dyn", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 max_mplex_dyn = null;
                
  
        @ASN1Element ( name = "cm-elem-info-list", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_CmplxElemInfoList cm_elem_info_list = null;
                
  
        
        public INT_U8 getMax_mplex_obs () {
            return this.max_mplex_obs;
        }

        

        public void setMax_mplex_obs (INT_U8 value) {
            this.max_mplex_obs = value;
        }
        
  
        
        public INT_U8 getMax_mplex_dyn () {
            return this.max_mplex_dyn;
        }

        

        public void setMax_mplex_dyn (INT_U8 value) {
            this.max_mplex_dyn = value;
        }
        
  
        
        public Poc_CmplxElemInfoList getCm_elem_info_list () {
            return this.cm_elem_info_list;
        }

        

        public void setCm_elem_info_list (Poc_CmplxElemInfoList value) {
            this.cm_elem_info_list = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_CmplxMetricInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            