
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_OpDeleteEntry", isSet = false )
    public class Poc_OpDeleteEntry implements IASN1PreparedElement {
            
        @ASN1Element ( name = "sco-glb-handle", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_GLB_HANDLE sco_glb_handle = null;
                
  
@ASN1SequenceOf( name = "deleted-op-list", isSetOf = false ) 

    
        @ASN1Element ( name = "deleted-op-list", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private java.util.Collection<Poc_OpElem>  deleted_op_list = null;
                
  
        
        public Poc_GLB_HANDLE getSco_glb_handle () {
            return this.sco_glb_handle;
        }

        

        public void setSco_glb_handle (Poc_GLB_HANDLE value) {
            this.sco_glb_handle = value;
        }
        
  
        
        public java.util.Collection<Poc_OpElem>  getDeleted_op_list () {
            return this.deleted_op_list;
        }

        

        public void setDeleted_op_list (java.util.Collection<Poc_OpElem>  value) {
            this.deleted_op_list = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_OpDeleteEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            