
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_MetricSpec", isSet = false )
    public class Poc_MetricSpec implements IASN1PreparedElement {
            
        @ASN1Element ( name = "update-period", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RelativeTime update_period = null;
                
  
        @ASN1Element ( name = "category", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_MetricCategory category = null;
                
  
        @ASN1Element ( name = "access", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_MetricAccess access = null;
                
  
        @ASN1Element ( name = "structure", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_MetricStructure structure = null;
                
  
        @ASN1Element ( name = "relevance", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_MetricRelevance relevance = null;
                
  
        
        public RelativeTime getUpdate_period () {
            return this.update_period;
        }

        

        public void setUpdate_period (RelativeTime value) {
            this.update_period = value;
        }
        
  
        
        public Poc_MetricCategory getCategory () {
            return this.category;
        }

        

        public void setCategory (Poc_MetricCategory value) {
            this.category = value;
        }
        
  
        
        public Poc_MetricAccess getAccess () {
            return this.access;
        }

        

        public void setAccess (Poc_MetricAccess value) {
            this.access = value;
        }
        
  
        
        public Poc_MetricStructure getStructure () {
            return this.structure;
        }

        

        public void setStructure (Poc_MetricStructure value) {
            this.structure = value;
        }
        
  
        
        public Poc_MetricRelevance getRelevance () {
            return this.relevance;
        }

        

        public void setRelevance (Poc_MetricRelevance value) {
            this.relevance = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_MetricSpec.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            