
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_OpGrouping", isSet = false )
    public class Poc_OpGrouping implements IASN1PreparedElement {
            
        @ASN1Element ( name = "group", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 group = null;
                
  
        @ASN1Element ( name = "priority", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 priority = null;
                
  
        
        public INT_U8 getGroup () {
            return this.group;
        }

        

        public void setGroup (INT_U8 value) {
            this.group = value;
        }
        
  
        
        public INT_U8 getPriority () {
            return this.priority;
        }

        

        public void setPriority (INT_U8 value) {
            this.priority = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_OpGrouping.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            