
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_ManagedObjectId", isSet = false )
    public class Poc_ManagedObjectId implements IASN1PreparedElement {
            
        @ASN1Element ( name = "m-obj-class", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type m_obj_class = null;
                
  
        @ASN1Element ( name = "m-obj-inst", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_GLB_HANDLE m_obj_inst = null;
                
  
        
        public OID_Type getM_obj_class () {
            return this.m_obj_class;
        }

        

        public void setM_obj_class (OID_Type value) {
            this.m_obj_class = value;
        }
        
  
        
        public Poc_GLB_HANDLE getM_obj_inst () {
            return this.m_obj_inst;
        }

        

        public void setM_obj_inst (Poc_GLB_HANDLE value) {
            this.m_obj_inst = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_ManagedObjectId.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            