
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_StepWidthEntry", isSet = false )
    public class Poc_StepWidthEntry implements IASN1PreparedElement {
            
        @ASN1Element ( name = "upper-edge", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private FLOAT_Type upper_edge = null;
                
  
        @ASN1Element ( name = "step-width", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private FLOAT_Type step_width = null;
                
  
        
        public FLOAT_Type getUpper_edge () {
            return this.upper_edge;
        }

        

        public void setUpper_edge (FLOAT_Type value) {
            this.upper_edge = value;
        }
        
  
        
        public FLOAT_Type getStep_width () {
            return this.step_width;
        }

        

        public void setStep_width (FLOAT_Type value) {
            this.step_width = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_StepWidthEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            