
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_Date", isSet = false )
    public class Poc_Date implements IASN1PreparedElement {
            
        @ASN1Element ( name = "century", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 century = null;
                
  
        @ASN1Element ( name = "year", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 year = null;
                
  
        @ASN1Element ( name = "month", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 month = null;
                
  
        @ASN1Element ( name = "day", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 day = null;
                
  
        
        public INT_U8 getCentury () {
            return this.century;
        }

        

        public void setCentury (INT_U8 value) {
            this.century = value;
        }
        
  
        
        public INT_U8 getYear () {
            return this.year;
        }

        

        public void setYear (INT_U8 value) {
            this.year = value;
        }
        
  
        
        public INT_U8 getMonth () {
            return this.month;
        }

        

        public void setMonth (INT_U8 value) {
            this.month = value;
        }
        
  
        
        public INT_U8 getDay () {
            return this.day;
        }

        

        public void setDay (INT_U8 value) {
            this.day = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_Date.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            