
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_ActionResult", isSet = false )
    public class Poc_ActionResult implements IASN1PreparedElement {
            
        @ASN1Element ( name = "managedObject", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_ManagedObjectId managedObject = null;
                
  
        @ASN1Element ( name = "actionReply", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_ActionReply actionReply = null;
                
  
        
        public Poc_ManagedObjectId getManagedObject () {
            return this.managedObject;
        }

        

        public void setManagedObject (Poc_ManagedObjectId value) {
            this.managedObject = value;
        }
        
  
        
        public Poc_ActionReply getActionReply () {
            return this.actionReply;
        }

        

        public void setActionReply (Poc_ActionReply value) {
            this.actionReply = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_ActionResult.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            