
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_SNTPTimeStamp", isSet = false )
    public class Poc_SNTPTimeStamp implements IASN1PreparedElement {
            
        @ASN1Element ( name = "seconds", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 seconds = null;
                
  
        @ASN1Element ( name = "fraction", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 fraction = null;
                
  
        
        public INT_U32 getSeconds () {
            return this.seconds;
        }

        

        public void setSeconds (INT_U32 value) {
            this.seconds = value;
        }
        
  
        
        public INT_U32 getFraction () {
            return this.fraction;
        }

        

        public void setFraction (INT_U32 value) {
            this.fraction = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_SNTPTimeStamp.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            