
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_AbsoluteRelativeTimeSync", isSet = false )
    public class Poc_AbsoluteRelativeTimeSync implements IASN1PreparedElement {
            
        @ASN1Element ( name = "absolute-time-mark", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AbsoluteTime absolute_time_mark = null;
                
  
        @ASN1Element ( name = "relative-time-mark", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RelativeTime relative_time_mark = null;
                
  
        @ASN1Element ( name = "relative-rollovers", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 relative_rollovers = null;
                
  
        @ASN1Element ( name = "hires-time-mark", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private HighResRelativeTime hires_time_mark = null;
                
  
        @ASN1Element ( name = "ext-time-marks", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_ExtTimeStampList ext_time_marks = null;
                
  
        
        public AbsoluteTime getAbsolute_time_mark () {
            return this.absolute_time_mark;
        }

        

        public void setAbsolute_time_mark (AbsoluteTime value) {
            this.absolute_time_mark = value;
        }
        
  
        
        public RelativeTime getRelative_time_mark () {
            return this.relative_time_mark;
        }

        

        public void setRelative_time_mark (RelativeTime value) {
            this.relative_time_mark = value;
        }
        
  
        
        public INT_U16 getRelative_rollovers () {
            return this.relative_rollovers;
        }

        

        public void setRelative_rollovers (INT_U16 value) {
            this.relative_rollovers = value;
        }
        
  
        
        public HighResRelativeTime getHires_time_mark () {
            return this.hires_time_mark;
        }

        

        public void setHires_time_mark (HighResRelativeTime value) {
            this.hires_time_mark = value;
        }
        
  
        
        public Poc_ExtTimeStampList getExt_time_marks () {
            return this.ext_time_marks;
        }

        

        public void setExt_time_marks (Poc_ExtTimeStampList value) {
            this.ext_time_marks = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_AbsoluteRelativeTimeSync.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            