
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_ExtNomenRef", isSet = false )
    public class Poc_ExtNomenRef implements IASN1PreparedElement {
            
        @ASN1Element ( name = "nomenclature-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type nomenclature_id = null;
                
  @ASN1Any( name = "" )
    
        @ASN1Element ( name = "nomenclature-code", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] nomenclature_code = null;
                
  
        
        public OID_Type getNomenclature_id () {
            return this.nomenclature_id;
        }

        

        public void setNomenclature_id (OID_Type value) {
            this.nomenclature_id = value;
        }
        
  
        
        public byte[] getNomenclature_code () {
            return this.nomenclature_code;
        }

        

        public void setNomenclature_code (byte[] value) {
            this.nomenclature_code = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_ExtNomenRef.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            