
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_SaSignalFrequency", isSet = false )
    public class Poc_SaSignalFrequency implements IASN1PreparedElement {
            
        @ASN1Element ( name = "low-edge-freq", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private FLOAT_Type low_edge_freq = null;
                
  
        @ASN1Element ( name = "high-edge-freq", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private FLOAT_Type high_edge_freq = null;
                
  
        
        public FLOAT_Type getLow_edge_freq () {
            return this.low_edge_freq;
        }

        

        public void setLow_edge_freq (FLOAT_Type value) {
            this.low_edge_freq = value;
        }
        
  
        
        public FLOAT_Type getHigh_edge_freq () {
            return this.high_edge_freq;
        }

        

        public void setHigh_edge_freq (FLOAT_Type value) {
            this.high_edge_freq = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_SaSignalFrequency.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            