
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_LeapSecondsTransition", isSet = false )
    public class Poc_LeapSecondsTransition implements IASN1PreparedElement {
            
        @ASN1Element ( name = "transition-date", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_Date transition_date = null;
                
  
        @ASN1Element ( name = "next-cum-leap-seconds", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 next_cum_leap_seconds = null;
                
  
        
        public Poc_Date getTransition_date () {
            return this.transition_date;
        }

        

        public void setTransition_date (Poc_Date value) {
            this.transition_date = value;
        }
        
  
        
        public INT_U32 getNext_cum_leap_seconds () {
            return this.next_cum_leap_seconds;
        }

        

        public void setNext_cum_leap_seconds (INT_U32 value) {
            this.next_cum_leap_seconds = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_LeapSecondsTransition.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            