
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_EventReportArgument", isSet = false )
    public class Poc_EventReportArgument implements IASN1PreparedElement {
            
        @ASN1Element ( name = "managedObject", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_ManagedObjectId managedObject = null;
                
  
        @ASN1Element ( name = "eventTime", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RelativeTime eventTime = null;
                
  
        @ASN1Element ( name = "eventType", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type eventType = null;
                
  @ASN1Any( name = "" )
    
        @ASN1Element ( name = "eventInfo", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] eventInfo = null;
                
  
        
        public Poc_ManagedObjectId getManagedObject () {
            return this.managedObject;
        }

        

        public void setManagedObject (Poc_ManagedObjectId value) {
            this.managedObject = value;
        }
        
  
        
        public RelativeTime getEventTime () {
            return this.eventTime;
        }

        

        public void setEventTime (RelativeTime value) {
            this.eventTime = value;
        }
        
  
        
        public OID_Type getEventType () {
            return this.eventType;
        }

        

        public void setEventType (OID_Type value) {
            this.eventType = value;
        }
        
  
        
        public byte[] getEventInfo () {
            return this.eventInfo;
        }

        

        public void setEventInfo (byte[] value) {
            this.eventInfo = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_EventReportArgument.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            