
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_DateTimeStatus", isSet = false )
    public class Poc_DateTimeStatus implements IASN1PreparedElement {
            
        @ASN1Element ( name = "usage-status", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_DateTimeUsage usage_status = null;
                
  
        @ASN1Element ( name = "clock-last-set", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AbsoluteTime clock_last_set = null;
                
  
        @ASN1Element ( name = "clock-accuracy", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private FLOAT_Type clock_accuracy = null;
                
  
        @ASN1Element ( name = "active-sync-protocol", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private TimeProtocolId active_sync_protocol = null;
                
  
        
        public Poc_DateTimeUsage getUsage_status () {
            return this.usage_status;
        }

        

        public void setUsage_status (Poc_DateTimeUsage value) {
            this.usage_status = value;
        }
        
  
        
        public AbsoluteTime getClock_last_set () {
            return this.clock_last_set;
        }

        

        public void setClock_last_set (AbsoluteTime value) {
            this.clock_last_set = value;
        }
        
  
        
        public FLOAT_Type getClock_accuracy () {
            return this.clock_accuracy;
        }

        

        public void setClock_accuracy (FLOAT_Type value) {
            this.clock_accuracy = value;
        }
        
  
        
        public TimeProtocolId getActive_sync_protocol () {
            return this.active_sync_protocol;
        }

        

        public void setActive_sync_protocol (TimeProtocolId value) {
            this.active_sync_protocol = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_DateTimeStatus.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            