
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "Poc_EnumVal" )
    public class Poc_EnumVal implements IASN1PreparedElement {
            
        @ASN1Element ( name = "enum-obj-id", isOptional =  false , hasTag =  true, tag = 1, isImplicitTag = false  , hasDefaultValue =  false  )
    
	private OID_Type enum_obj_id = null;
                
  @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "enum-text-string", isOptional =  false , hasTag =  true, tag = 2, isImplicitTag = false  , hasDefaultValue =  false  )
    
	private byte[] enum_text_string = null;
                
  
        @ASN1Element ( name = "enum-external-code", isOptional =  false , hasTag =  true, tag = 8, isImplicitTag = false  , hasDefaultValue =  false  )
    
	private Poc_ExtNomenRef enum_external_code = null;
                
  
        @ASN1Element ( name = "enum-bit-str", isOptional =  false , hasTag =  true, tag = 16, isImplicitTag = false  , hasDefaultValue =  false  )
    
	private BITS_32 enum_bit_str = null;
                
  
        @ASN1Element ( name = "enum-record-metric", isOptional =  false , hasTag =  true, tag = 33, isImplicitTag = false  , hasDefaultValue =  false  )
    
	private Poc_EnumRecordMetric enum_record_metric = null;
                
  
        @ASN1Element ( name = "enum-record-oo", isOptional =  false , hasTag =  true, tag = 34, isImplicitTag = false  , hasDefaultValue =  false  )
    
	private Poc_EnumRecordOo enum_record_oo = null;
                
  
        @ASN1Element ( name = "enum-numeral", isOptional =  false , hasTag =  true, tag = 64, isImplicitTag = false  , hasDefaultValue =  false  )
    
	private INT_U32 enum_numeral = null;
                
  
        
        public OID_Type getEnum_obj_id () {
            return this.enum_obj_id;
        }

        public boolean isEnum_obj_idSelected () {
            return this.enum_obj_id != null;
        }

        private void setEnum_obj_id (OID_Type value) {
            this.enum_obj_id = value;
        }

        
        public void selectEnum_obj_id (OID_Type value) {
            this.enum_obj_id = value;
            
                    setEnum_text_string(null);
                
                    setEnum_external_code(null);
                
                    setEnum_bit_str(null);
                
                    setEnum_record_metric(null);
                
                    setEnum_record_oo(null);
                
                    setEnum_numeral(null);
                            
        }

        
  
        
        public byte[] getEnum_text_string () {
            return this.enum_text_string;
        }

        public boolean isEnum_text_stringSelected () {
            return this.enum_text_string != null;
        }

        private void setEnum_text_string (byte[] value) {
            this.enum_text_string = value;
        }

        
        public void selectEnum_text_string (byte[] value) {
            this.enum_text_string = value;
            
                    setEnum_obj_id(null);
                
                    setEnum_external_code(null);
                
                    setEnum_bit_str(null);
                
                    setEnum_record_metric(null);
                
                    setEnum_record_oo(null);
                
                    setEnum_numeral(null);
                            
        }

        
  
        
        public Poc_ExtNomenRef getEnum_external_code () {
            return this.enum_external_code;
        }

        public boolean isEnum_external_codeSelected () {
            return this.enum_external_code != null;
        }

        private void setEnum_external_code (Poc_ExtNomenRef value) {
            this.enum_external_code = value;
        }

        
        public void selectEnum_external_code (Poc_ExtNomenRef value) {
            this.enum_external_code = value;
            
                    setEnum_obj_id(null);
                
                    setEnum_text_string(null);
                
                    setEnum_bit_str(null);
                
                    setEnum_record_metric(null);
                
                    setEnum_record_oo(null);
                
                    setEnum_numeral(null);
                            
        }

        
  
        
        public BITS_32 getEnum_bit_str () {
            return this.enum_bit_str;
        }

        public boolean isEnum_bit_strSelected () {
            return this.enum_bit_str != null;
        }

        private void setEnum_bit_str (BITS_32 value) {
            this.enum_bit_str = value;
        }

        
        public void selectEnum_bit_str (BITS_32 value) {
            this.enum_bit_str = value;
            
                    setEnum_obj_id(null);
                
                    setEnum_text_string(null);
                
                    setEnum_external_code(null);
                
                    setEnum_record_metric(null);
                
                    setEnum_record_oo(null);
                
                    setEnum_numeral(null);
                            
        }

        
  
        
        public Poc_EnumRecordMetric getEnum_record_metric () {
            return this.enum_record_metric;
        }

        public boolean isEnum_record_metricSelected () {
            return this.enum_record_metric != null;
        }

        private void setEnum_record_metric (Poc_EnumRecordMetric value) {
            this.enum_record_metric = value;
        }

        
        public void selectEnum_record_metric (Poc_EnumRecordMetric value) {
            this.enum_record_metric = value;
            
                    setEnum_obj_id(null);
                
                    setEnum_text_string(null);
                
                    setEnum_external_code(null);
                
                    setEnum_bit_str(null);
                
                    setEnum_record_oo(null);
                
                    setEnum_numeral(null);
                            
        }

        
  
        
        public Poc_EnumRecordOo getEnum_record_oo () {
            return this.enum_record_oo;
        }

        public boolean isEnum_record_ooSelected () {
            return this.enum_record_oo != null;
        }

        private void setEnum_record_oo (Poc_EnumRecordOo value) {
            this.enum_record_oo = value;
        }

        
        public void selectEnum_record_oo (Poc_EnumRecordOo value) {
            this.enum_record_oo = value;
            
                    setEnum_obj_id(null);
                
                    setEnum_text_string(null);
                
                    setEnum_external_code(null);
                
                    setEnum_bit_str(null);
                
                    setEnum_record_metric(null);
                
                    setEnum_numeral(null);
                            
        }

        
  
        
        public INT_U32 getEnum_numeral () {
            return this.enum_numeral;
        }

        public boolean isEnum_numeralSelected () {
            return this.enum_numeral != null;
        }

        private void setEnum_numeral (INT_U32 value) {
            this.enum_numeral = value;
        }

        
        public void selectEnum_numeral (INT_U32 value) {
            this.enum_numeral = value;
            
                    setEnum_obj_id(null);
                
                    setEnum_text_string(null);
                
                    setEnum_external_code(null);
                
                    setEnum_bit_str(null);
                
                    setEnum_record_metric(null);
                
                    setEnum_record_oo(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_EnumVal.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            