
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_ArchiveProtection", isSet = false )
    public class Poc_ArchiveProtection implements IASN1PreparedElement {
            
        @ASN1Element ( name = "protection-type", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private PrivateOid protection_type = null;
                
  @ASN1Any( name = "" )
    
        @ASN1Element ( name = "protection-key", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] protection_key = null;
                
  
        
        public PrivateOid getProtection_type () {
            return this.protection_type;
        }

        

        public void setProtection_type (PrivateOid value) {
            this.protection_type = value;
        }
        
  
        
        public byte[] getProtection_key () {
            return this.protection_key;
        }

        

        public void setProtection_key (byte[] value) {
            this.protection_key = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_ArchiveProtection.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            