
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_MarkerEntryRelTim", isSet = false )
    public class Poc_MarkerEntryRelTim implements IASN1PreparedElement {
            
        @ASN1Element ( name = "marker-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type marker_id = null;
                
  
        @ASN1Element ( name = "marker-time", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RelativeTime marker_time = null;
                
  
        
        public OID_Type getMarker_id () {
            return this.marker_id;
        }

        

        public void setMarker_id (OID_Type value) {
            this.marker_id = value;
        }
        
  
        
        public RelativeTime getMarker_time () {
            return this.marker_time;
        }

        

        public void setMarker_time (RelativeTime value) {
            this.marker_time = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_MarkerEntryRelTim.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            