
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_ProcessingFailure", isSet = false )
    public class Poc_ProcessingFailure implements IASN1PreparedElement {
            
        @ASN1Element ( name = "error-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type error_id = null;
                
  @ASN1Any( name = "" )
    
        @ASN1Element ( name = "error-info", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] error_info = null;
                
  
        
        public OID_Type getError_id () {
            return this.error_id;
        }

        

        public void setError_id (OID_Type value) {
            this.error_id = value;
        }
        
  
        
        public byte[] getError_info () {
            return this.error_info;
        }

        

        public void setError_info (byte[] value) {
            this.error_info = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_ProcessingFailure.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            