
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "Poc_MdsSetStateResult" )
    public class Poc_MdsSetStateResult implements IASN1PreparedElement {
                
        
        @ASN1Element ( name = "Poc-MdsSetStateResult", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
        private Poc_MDSStatus  value;        

        
        
        public Poc_MdsSetStateResult () {
        }
        
        
        
        public void setValue(Poc_MDSStatus value) {
            this.value = value;
        }
        
        
        
        public Poc_MDSStatus getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_MdsSetStateResult.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            