
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_DaylightSavingsTransition", isSet = false )
    public class Poc_DaylightSavingsTransition implements IASN1PreparedElement {
            
        @ASN1Element ( name = "transition-date", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AbsoluteTime transition_date = null;
                
  
        @ASN1Element ( name = "next-offset", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_UTCTimeZone next_offset = null;
                
  
        
        public AbsoluteTime getTransition_date () {
            return this.transition_date;
        }

        

        public void setTransition_date (AbsoluteTime value) {
            this.transition_date = value;
        }
        
  
        
        public Poc_UTCTimeZone getNext_offset () {
            return this.next_offset;
        }

        

        public void setNext_offset (Poc_UTCTimeZone value) {
            this.next_offset = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_DaylightSavingsTransition.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            