
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_AlertCapabEntry", isSet = false )
    public class Poc_AlertCapabEntry implements IASN1PreparedElement {
            
        @ASN1Element ( name = "obj-reference", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private HANDLE obj_reference = null;
                
  
        @ASN1Element ( name = "obj-class", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type obj_class = null;
                
  
        @ASN1Element ( name = "alert-group", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type alert_group = null;
                
  @ASN1BitString( name = "" )
    
            @ASN1SizeConstraint ( max = 16L )
        
        @ASN1Element ( name = "al-rep-flags", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private BitString al_rep_flags = null;
                
  
        @ASN1Element ( name = "max-t-severity", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_AlertType max_t_severity = null;
                
  
        @ASN1Element ( name = "max-t-obj-al", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 max_t_obj_al = null;
                
  
        @ASN1Element ( name = "max-p-severity", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_AlertType max_p_severity = null;
                
  
        @ASN1Element ( name = "max-p-obj-al", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 max_p_obj_al = null;
                
  
        
        public HANDLE getObj_reference () {
            return this.obj_reference;
        }

        

        public void setObj_reference (HANDLE value) {
            this.obj_reference = value;
        }
        
  
        
        public OID_Type getObj_class () {
            return this.obj_class;
        }

        

        public void setObj_class (OID_Type value) {
            this.obj_class = value;
        }
        
  
        
        public OID_Type getAlert_group () {
            return this.alert_group;
        }

        

        public void setAlert_group (OID_Type value) {
            this.alert_group = value;
        }
        
  
        
        public BitString getAl_rep_flags () {
            return this.al_rep_flags;
        }

        

        public void setAl_rep_flags (BitString value) {
            this.al_rep_flags = value;
        }
        
  
        
        public Poc_AlertType getMax_t_severity () {
            return this.max_t_severity;
        }

        

        public void setMax_t_severity (Poc_AlertType value) {
            this.max_t_severity = value;
        }
        
  
        
        public INT_U16 getMax_t_obj_al () {
            return this.max_t_obj_al;
        }

        

        public void setMax_t_obj_al (INT_U16 value) {
            this.max_t_obj_al = value;
        }
        
  
        
        public Poc_AlertType getMax_p_severity () {
            return this.max_p_severity;
        }

        

        public void setMax_p_severity (Poc_AlertType value) {
            this.max_p_severity = value;
        }
        
  
        
        public INT_U16 getMax_p_obj_al () {
            return this.max_p_obj_al;
        }

        

        public void setMax_p_obj_al (INT_U16 value) {
            this.max_p_obj_al = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_AlertCapabEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            