
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_ClockStatusUpdateInfo", isSet = false )
    public class Poc_ClockStatusUpdateInfo implements IASN1PreparedElement {
            
        @ASN1Element ( name = "date-time-status", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_DateTimeStatus date_time_status = null;
                
  
        @ASN1Element ( name = "time-sync", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_AbsoluteRelativeTimeSync time_sync = null;
                
  
        
        public Poc_DateTimeStatus getDate_time_status () {
            return this.date_time_status;
        }

        

        public void setDate_time_status (Poc_DateTimeStatus value) {
            this.date_time_status = value;
        }
        
  
        
        public Poc_AbsoluteRelativeTimeSync getTime_sync () {
            return this.time_sync;
        }

        

        public void setTime_sync (Poc_AbsoluteRelativeTimeSync value) {
            this.time_sync = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_ClockStatusUpdateInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            