
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_OpDeleteInfo", isSet = false )
    public class Poc_OpDeleteInfo implements IASN1PreparedElement {
            
        @ASN1Element ( name = "scan-report-no", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 scan_report_no = null;
                
  
@ASN1SequenceOf( name = "deleted-op-list", isSetOf = false ) 

    
        @ASN1Element ( name = "deleted-op-list", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private java.util.Collection<Poc_OpDeleteEntry>  deleted_op_list = null;
                
  
        
        public INT_U16 getScan_report_no () {
            return this.scan_report_no;
        }

        

        public void setScan_report_no (INT_U16 value) {
            this.scan_report_no = value;
        }
        
  
        
        public java.util.Collection<Poc_OpDeleteEntry>  getDeleted_op_list () {
            return this.deleted_op_list;
        }

        

        public void setDeleted_op_list (java.util.Collection<Poc_OpDeleteEntry>  value) {
            this.deleted_op_list = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_OpDeleteInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            