
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_OperSpec", isSet = false )
    public class Poc_OperSpec implements IASN1PreparedElement {
            
        @ASN1Element ( name = "vattr-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type vattr_id = null;
                
  
        @ASN1Element ( name = "op-target", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type op_target = null;
                
  
        @ASN1Element ( name = "options", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_OpOptions options = null;
                
  
        @ASN1Element ( name = "level", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_OpLevel level = null;
                
  
        @ASN1Element ( name = "grouping", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_OpGrouping grouping = null;
                
  
        
        public OID_Type getVattr_id () {
            return this.vattr_id;
        }

        

        public void setVattr_id (OID_Type value) {
            this.vattr_id = value;
        }
        
  
        
        public OID_Type getOp_target () {
            return this.op_target;
        }

        

        public void setOp_target (OID_Type value) {
            this.op_target = value;
        }
        
  
        
        public Poc_OpOptions getOptions () {
            return this.options;
        }

        

        public void setOptions (Poc_OpOptions value) {
            this.options = value;
        }
        
  
        
        public Poc_OpLevel getLevel () {
            return this.level;
        }

        

        public void setLevel (Poc_OpLevel value) {
            this.level = value;
        }
        
  
        
        public Poc_OpGrouping getGrouping () {
            return this.grouping;
        }

        

        public void setGrouping (Poc_OpGrouping value) {
            this.grouping = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_OperSpec.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            