
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_UTCTimeZone", isSet = false )
    public class Poc_UTCTimeZone implements IASN1PreparedElement {
            
        @ASN1Element ( name = "time-zone-offset-hours", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_I8 time_zone_offset_hours = null;
                
  
        @ASN1Element ( name = "time-zone-offset-minutes", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U8 time_zone_offset_minutes = null;
                
  @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "time-zone-label", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] time_zone_label = null;
                
  
        
        public INT_I8 getTime_zone_offset_hours () {
            return this.time_zone_offset_hours;
        }

        

        public void setTime_zone_offset_hours (INT_I8 value) {
            this.time_zone_offset_hours = value;
        }
        
  
        
        public INT_U8 getTime_zone_offset_minutes () {
            return this.time_zone_offset_minutes;
        }

        

        public void setTime_zone_offset_minutes (INT_U8 value) {
            this.time_zone_offset_minutes = value;
        }
        
  
        
        public byte[] getTime_zone_label () {
            return this.time_zone_label;
        }

        

        public void setTime_zone_label (byte[] value) {
            this.time_zone_label = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_UTCTimeZone.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            