
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_RtsaObservationScan", isSet = false )
    public class Poc_RtsaObservationScan implements IASN1PreparedElement {
            
        @ASN1Element ( name = "handle", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private HANDLE handle = null;
                
  
        @ASN1Element ( name = "observation", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_SaObsValue observation = null;
                
  
        
        public HANDLE getHandle () {
            return this.handle;
        }

        

        public void setHandle (HANDLE value) {
            this.handle = value;
        }
        
  
        
        public Poc_SaObsValue getObservation () {
            return this.observation;
        }

        

        public void setObservation (Poc_SaObsValue value) {
            this.observation = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_RtsaObservationScan.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            