
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_Authorization", isSet = false )
    public class Poc_Authorization implements IASN1PreparedElement {
            
        @ASN1Element ( name = "authorization-type", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private PrivateOid authorization_type = null;
                
  @ASN1Any( name = "" )
    
        @ASN1Element ( name = "authorization-key", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] authorization_key = null;
                
  
        
        public PrivateOid getAuthorization_type () {
            return this.authorization_type;
        }

        

        public void setAuthorization_type (PrivateOid value) {
            this.authorization_type = value;
        }
        
  
        
        public byte[] getAuthorization_key () {
            return this.authorization_key;
        }

        

        public void setAuthorization_key (byte[] value) {
            this.authorization_key = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_Authorization.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            