
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_RefreshObjEntry", isSet = false )
    public class Poc_RefreshObjEntry implements IASN1PreparedElement {
            
        @ASN1Element ( name = "object-glb-handle", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_GLB_HANDLE object_glb_handle = null;
                
  
        @ASN1Element ( name = "scanned-attribute", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type scanned_attribute = null;
                
  
        
        public Poc_GLB_HANDLE getObject_glb_handle () {
            return this.object_glb_handle;
        }

        

        public void setObject_glb_handle (Poc_GLB_HANDLE value) {
            this.object_glb_handle = value;
        }
        
  
        
        public OID_Type getScanned_attribute () {
            return this.scanned_attribute;
        }

        

        public void setScanned_attribute (OID_Type value) {
            this.scanned_attribute = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_RefreshObjEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            