
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "Poc_OpInvokeList" )
    public class Poc_OpInvokeList implements IASN1PreparedElement {
                
            
            @ASN1SequenceOf( name = "Poc-OpInvokeList" , isSetOf = false)
	    private java.util.Collection<Poc_OpInvokeElement> value = null; 
    
            public Poc_OpInvokeList () {
            }
        
            public Poc_OpInvokeList ( java.util.Collection<Poc_OpInvokeElement> value ) {
                setValue(value);
            }
                        
            public void setValue(java.util.Collection<Poc_OpInvokeElement> value) {
                this.value = value;
            }
            
            public java.util.Collection<Poc_OpInvokeElement> getValue() {
                return this.value;
            }            
            
            public void initValue() {
                setValue(new java.util.LinkedList<Poc_OpInvokeElement>()); 
            }
            
            public void add(Poc_OpInvokeElement item) {
                value.add(item);
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_OpInvokeList.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            