
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "Poc_CtxtHelp" )
    public class Poc_CtxtHelp implements IASN1PreparedElement {
            @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "text-string", isOptional =  false , hasTag =  true, tag = 1, isImplicitTag = false  , hasDefaultValue =  false  )
    
	private byte[] text_string = null;
                
  
        @ASN1Element ( name = "oid", isOptional =  false , hasTag =  true, tag = 8, isImplicitTag = false  , hasDefaultValue =  false  )
    
	private OID_Type oid = null;
                
  
        
        public byte[] getText_string () {
            return this.text_string;
        }

        public boolean isText_stringSelected () {
            return this.text_string != null;
        }

        private void setText_string (byte[] value) {
            this.text_string = value;
        }

        
        public void selectText_string (byte[] value) {
            this.text_string = value;
            
                    setOid(null);
                            
        }

        
  
        
        public OID_Type getOid () {
            return this.oid;
        }

        public boolean isOidSelected () {
            return this.oid != null;
        }

        private void setOid (OID_Type value) {
            this.oid = value;
        }

        
        public void selectOid (OID_Type value) {
            this.oid = value;
            
                    setText_string(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_CtxtHelp.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            