
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "Poc_CC_Oid" )
    public class Poc_CC_Oid implements IASN1PreparedElement {
                
        
        @ASN1Element ( name = "Poc-CC-Oid", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
        private OID_Type  value;        

        
        
        public Poc_CC_Oid () {
        }
        
        
        
        public void setValue(OID_Type value) {
            this.value = value;
        }
        
        
        
        public OID_Type getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_CC_Oid.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            