
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_DevAlarmEntry", isSet = false )
    public class Poc_DevAlarmEntry implements IASN1PreparedElement {
            
        @ASN1Element ( name = "al-source", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type al_source = null;
                
  
        @ASN1Element ( name = "al-code", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type al_code = null;
                
  
        @ASN1Element ( name = "al-type", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_AlertType al_type = null;
                
  
        @ASN1Element ( name = "al-state", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_AlertState al_state = null;
                
  
        @ASN1Element ( name = "object", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_ManagedObjectId object = null;
                
  
        @ASN1Element ( name = "alert-info-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private PrivateOid alert_info_id = null;
                
  @ASN1Any( name = "" )
    
        @ASN1Element ( name = "alert-info", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] alert_info = null;
                
  
        
        public OID_Type getAl_source () {
            return this.al_source;
        }

        

        public void setAl_source (OID_Type value) {
            this.al_source = value;
        }
        
  
        
        public OID_Type getAl_code () {
            return this.al_code;
        }

        

        public void setAl_code (OID_Type value) {
            this.al_code = value;
        }
        
  
        
        public Poc_AlertType getAl_type () {
            return this.al_type;
        }

        

        public void setAl_type (Poc_AlertType value) {
            this.al_type = value;
        }
        
  
        
        public Poc_AlertState getAl_state () {
            return this.al_state;
        }

        

        public void setAl_state (Poc_AlertState value) {
            this.al_state = value;
        }
        
  
        
        public Poc_ManagedObjectId getObject () {
            return this.object;
        }

        

        public void setObject (Poc_ManagedObjectId value) {
            this.object = value;
        }
        
  
        
        public PrivateOid getAlert_info_id () {
            return this.alert_info_id;
        }

        

        public void setAlert_info_id (PrivateOid value) {
            this.alert_info_id = value;
        }
        
  
        
        public byte[] getAlert_info () {
            return this.alert_info;
        }

        

        public void setAlert_info (byte[] value) {
            this.alert_info = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_DevAlarmEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            