
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_VmoSourceEntry", isSet = false )
    public class Poc_VmoSourceEntry implements IASN1PreparedElement {
            
        @ASN1Element ( name = "vmo-type", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type vmo_type = null;
                
  
        @ASN1Element ( name = "glb-handle", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_GLB_HANDLE glb_handle = null;
                
  
        
        public OID_Type getVmo_type () {
            return this.vmo_type;
        }

        

        public void setVmo_type (OID_Type value) {
            this.vmo_type = value;
        }
        
  
        
        public Poc_GLB_HANDLE getGlb_handle () {
            return this.glb_handle;
        }

        

        public void setGlb_handle (Poc_GLB_HANDLE value) {
            this.glb_handle = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_VmoSourceEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            