
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_SystemSpecEntry", isSet = false )
    public class Poc_SystemSpecEntry implements IASN1PreparedElement {
            
        @ASN1Element ( name = "component-capab-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private PrivateOid component_capab_id = null;
                
  @ASN1Any( name = "" )
    
        @ASN1Element ( name = "component-spec", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] component_spec = null;
                
  
        
        public PrivateOid getComponent_capab_id () {
            return this.component_capab_id;
        }

        

        public void setComponent_capab_id (PrivateOid value) {
            this.component_capab_id = value;
        }
        
  
        
        public byte[] getComponent_spec () {
            return this.component_spec;
        }

        

        public void setComponent_spec (byte[] value) {
            this.component_spec = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_SystemSpecEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            