
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_ToggleLabelStrings", isSet = false )
    public class Poc_ToggleLabelStrings implements IASN1PreparedElement {
            @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "lbl-state0", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] lbl_state0 = null;
                
  @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "lbl-state1", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] lbl_state1 = null;
                
  
        
        public byte[] getLbl_state0 () {
            return this.lbl_state0;
        }

        

        public void setLbl_state0 (byte[] value) {
            this.lbl_state0 = value;
        }
        
  
        
        public byte[] getLbl_state1 () {
            return this.lbl_state1;
        }

        

        public void setLbl_state1 (byte[] value) {
            this.lbl_state1 = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_ToggleLabelStrings.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            