
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_MdsCreateInfo", isSet = false )
    public class Poc_MdsCreateInfo implements IASN1PreparedElement {
            
        @ASN1Element ( name = "class-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_ManagedObjectId class_id = null;
                
  
        @ASN1Element ( name = "attribute-list", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AttributeList attribute_list = null;
                
  
        
        public Poc_ManagedObjectId getClass_id () {
            return this.class_id;
        }

        

        public void setClass_id (Poc_ManagedObjectId value) {
            this.class_id = value;
        }
        
  
        
        public AttributeList getAttribute_list () {
            return this.attribute_list;
        }

        

        public void setAttribute_list (AttributeList value) {
            this.attribute_list = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_MdsCreateInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            