
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_OpAttributeScan", isSet = false )
    public class Poc_OpAttributeScan implements IASN1PreparedElement {
            
        @ASN1Element ( name = "sco-handle", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private HANDLE sco_handle = null;
                
  
        @ASN1Element ( name = "invoke-cookie", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 invoke_cookie = null;
                
  
        @ASN1Element ( name = "lock-state", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_AdministrativeState lock_state = null;
                
  
        @ASN1Element ( name = "op-elem-updt-list", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_OpElemAttrList op_elem_updt_list = null;
                
  
        
        public HANDLE getSco_handle () {
            return this.sco_handle;
        }

        

        public void setSco_handle (HANDLE value) {
            this.sco_handle = value;
        }
        
  
        
        public INT_U32 getInvoke_cookie () {
            return this.invoke_cookie;
        }

        

        public void setInvoke_cookie (INT_U32 value) {
            this.invoke_cookie = value;
        }
        
  
        
        public Poc_AdministrativeState getLock_state () {
            return this.lock_state;
        }

        

        public void setLock_state (Poc_AdministrativeState value) {
            this.lock_state = value;
        }
        
  
        
        public Poc_OpElemAttrList getOp_elem_updt_list () {
            return this.op_elem_updt_list;
        }

        

        public void setOp_elem_updt_list (Poc_OpElemAttrList value) {
            this.op_elem_updt_list = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_OpAttributeScan.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            