
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_OpCreateEntry", isSet = false )
    public class Poc_OpCreateEntry implements IASN1PreparedElement {
            
        @ASN1Element ( name = "sco-glb-handle", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_GLB_HANDLE sco_glb_handle = null;
                
  
        @ASN1Element ( name = "created-op-list", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_OpElemAttrList created_op_list = null;
                
  
        
        public Poc_GLB_HANDLE getSco_glb_handle () {
            return this.sco_glb_handle;
        }

        

        public void setSco_glb_handle (Poc_GLB_HANDLE value) {
            this.sco_glb_handle = value;
        }
        
  
        
        public Poc_OpElemAttrList getCreated_op_list () {
            return this.created_op_list;
        }

        

        public void setCreated_op_list (Poc_OpElemAttrList value) {
            this.created_op_list = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_OpCreateEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            