
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_LimitSpecEntry", isSet = false )
    public class Poc_LimitSpecEntry implements IASN1PreparedElement {
            
        @ASN1Element ( name = "object-handle", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private HANDLE object_handle = null;
                
  
        @ASN1Element ( name = "al-source-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type al_source_id = null;
                
  
        @ASN1Element ( name = "unit-code", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type unit_code = null;
                
  
        @ASN1Element ( name = "lim-al-stat", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_CurLimAlStat lim_al_stat = null;
                
  
        @ASN1Element ( name = "lim-al-val", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_CurLimAlVal lim_al_val = null;
                
  
        
        public HANDLE getObject_handle () {
            return this.object_handle;
        }

        

        public void setObject_handle (HANDLE value) {
            this.object_handle = value;
        }
        
  
        
        public OID_Type getAl_source_id () {
            return this.al_source_id;
        }

        

        public void setAl_source_id (OID_Type value) {
            this.al_source_id = value;
        }
        
  
        
        public OID_Type getUnit_code () {
            return this.unit_code;
        }

        

        public void setUnit_code (OID_Type value) {
            this.unit_code = value;
        }
        
  
        
        public Poc_CurLimAlStat getLim_al_stat () {
            return this.lim_al_stat;
        }

        

        public void setLim_al_stat (Poc_CurLimAlStat value) {
            this.lim_al_stat = value;
        }
        
  
        
        public Poc_CurLimAlVal getLim_al_val () {
            return this.lim_al_val;
        }

        

        public void setLim_al_val (Poc_CurLimAlVal value) {
            this.lim_al_val = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_LimitSpecEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            