
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_ActionInfo", isSet = false )
    public class Poc_ActionInfo implements IASN1PreparedElement {
            
        @ASN1Element ( name = "actionType", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type actionType = null;
                
  @ASN1Any( name = "" )
    
        @ASN1Element ( name = "actionInfoArgs", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] actionInfoArgs = null;
                
  
        
        public OID_Type getActionType () {
            return this.actionType;
        }

        

        public void setActionType (OID_Type value) {
            this.actionType = value;
        }
        
  
        
        public byte[] getActionInfoArgs () {
            return this.actionInfoArgs;
        }

        

        public void setActionInfoArgs (byte[] value) {
            this.actionInfoArgs = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_ActionInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            