
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_GetEventLogEntryResult", isSet = false )
    public class Poc_GetEventLogEntryResult implements IASN1PreparedElement {
            
        @ASN1Element ( name = "log-change-count", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 log_change_count = null;
                
  
        @ASN1Element ( name = "from-log-entry-index", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 from_log_entry_index = null;
                
  
        @ASN1Element ( name = "to-log-entry-index", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 to_log_entry_index = null;
                
  
        @ASN1Element ( name = "entry-list", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_EventLogEntryList entry_list = null;
                
  
        
        public INT_U16 getLog_change_count () {
            return this.log_change_count;
        }

        

        public void setLog_change_count (INT_U16 value) {
            this.log_change_count = value;
        }
        
  
        
        public INT_U32 getFrom_log_entry_index () {
            return this.from_log_entry_index;
        }

        

        public void setFrom_log_entry_index (INT_U32 value) {
            this.from_log_entry_index = value;
        }
        
  
        
        public INT_U32 getTo_log_entry_index () {
            return this.to_log_entry_index;
        }

        

        public void setTo_log_entry_index (INT_U32 value) {
            this.to_log_entry_index = value;
        }
        
  
        
        public Poc_EventLogEntryList getEntry_list () {
            return this.entry_list;
        }

        

        public void setEntry_list (Poc_EventLogEntryList value) {
            this.entry_list = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_GetEventLogEntryResult.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            