
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_ScoOperReqSpec", isSet = false )
    public class Poc_ScoOperReqSpec implements IASN1PreparedElement {
            
        @ASN1Element ( name = "op-req-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private PrivateOid op_req_id = null;
                
  @ASN1Any( name = "" )
    
        @ASN1Element ( name = "op-req-info", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] op_req_info = null;
                
  
        
        public PrivateOid getOp_req_id () {
            return this.op_req_id;
        }

        

        public void setOp_req_id (PrivateOid value) {
            this.op_req_id = value;
        }
        
  
        
        public byte[] getOp_req_info () {
            return this.op_req_info;
        }

        

        public void setOp_req_info (byte[] value) {
            this.op_req_info = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_ScoOperReqSpec.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            