
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_MarkerEntrySaVal32", isSet = false )
    public class Poc_MarkerEntrySaVal32 implements IASN1PreparedElement {
            
        @ASN1Element ( name = "marker-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type marker_id = null;
                
  
        @ASN1Element ( name = "marker-val", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 marker_val = null;
                
  
        
        public OID_Type getMarker_id () {
            return this.marker_id;
        }

        

        public void setMarker_id (OID_Type value) {
            this.marker_id = value;
        }
        
  
        
        public INT_U32 getMarker_val () {
            return this.marker_val;
        }

        

        public void setMarker_val (INT_U32 value) {
            this.marker_val = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_MarkerEntrySaVal32.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            