
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_SaGridEntry32", isSet = false )
    public class Poc_SaGridEntry32 implements IASN1PreparedElement {
            
        @ASN1Element ( name = "absolute-value", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private FLOAT_Type absolute_value = null;
                
  
        @ASN1Element ( name = "scaled-value", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U32 scaled_value = null;
                
  
        @ASN1Element ( name = "level", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private INT_U16 level = null;
                
  
        
        public FLOAT_Type getAbsolute_value () {
            return this.absolute_value;
        }

        

        public void setAbsolute_value (FLOAT_Type value) {
            this.absolute_value = value;
        }
        
  
        
        public INT_U32 getScaled_value () {
            return this.scaled_value;
        }

        

        public void setScaled_value (INT_U32 value) {
            this.scaled_value = value;
        }
        
  
        
        public INT_U16 getLevel () {
            return this.level;
        }

        

        public void setLevel (INT_U16 value) {
            this.level = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_SaGridEntry32.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            