
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_CmplxStaticAttr", isSet = false )
    public class Poc_CmplxStaticAttr implements IASN1PreparedElement {
            
        @ASN1Element ( name = "cm-static-elem-list", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_CmplxStaticAttrElemList cm_static_elem_list = null;
                
  
        
        public Poc_CmplxStaticAttrElemList getCm_static_elem_list () {
            return this.cm_static_elem_list;
        }

        

        public void setCm_static_elem_list (Poc_CmplxStaticAttrElemList value) {
            this.cm_static_elem_list = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_CmplxStaticAttr.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            