
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_SelectUValueEntry", isSet = false )
    public class Poc_SelectUValueEntry implements IASN1PreparedElement {
            
        @ASN1Element ( name = "value", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private FLOAT_Type value = null;
                
  
        @ASN1Element ( name = "m-units", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type m_units = null;
                
  
        
        public FLOAT_Type getValue () {
            return this.value;
        }

        

        public void setValue (FLOAT_Type value) {
            this.value = value;
        }
        
  
        
        public OID_Type getM_units () {
            return this.m_units;
        }

        

        public void setM_units (OID_Type value) {
            this.m_units = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_SelectUValueEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            