
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "Poc_SelectList" )
    public class Poc_SelectList implements IASN1PreparedElement {
            
@ASN1SequenceOf( name = "oid-list", isSetOf = false ) 

    
        @ASN1Element ( name = "oid-list", isOptional =  false , hasTag =  true, tag = 1, isImplicitTag = false  , hasDefaultValue =  false  )
    
	private java.util.Collection<OID_Type>  oid_list = null;
                
  
@ASN1SequenceOf( name = "value-list", isSetOf = false ) 

    
        @ASN1Element ( name = "value-list", isOptional =  false , hasTag =  true, tag = 3, isImplicitTag = false  , hasDefaultValue =  false  )
    
	private java.util.Collection<FLOAT_Type>  value_list = null;
                
  
@ASN1SequenceOf( name = "value-u-list", isSetOf = false ) 

    
        @ASN1Element ( name = "value-u-list", isOptional =  false , hasTag =  true, tag = 4, isImplicitTag = false  , hasDefaultValue =  false  )
    
	private java.util.Collection<Poc_SelectUValueEntry>  value_u_list = null;
                
  @ASN1OctetString( name = "" )
    
@ASN1SequenceOf( name = "string-list", isSetOf = false ) 

    
        @ASN1Element ( name = "string-list", isOptional =  false , hasTag =  true, tag = 5, isImplicitTag = false  , hasDefaultValue =  false  )
    
	private java.util.Collection<byte[]>  string_list = null;
                
  
        
        public java.util.Collection<OID_Type>  getOid_list () {
            return this.oid_list;
        }

        public boolean isOid_listSelected () {
            return this.oid_list != null;
        }

        private void setOid_list (java.util.Collection<OID_Type>  value) {
            this.oid_list = value;
        }

        
        public void selectOid_list (java.util.Collection<OID_Type>  value) {
            this.oid_list = value;
            
                    setValue_list(null);
                
                    setValue_u_list(null);
                
                    setString_list(null);
                            
        }

        
  
        
        public java.util.Collection<FLOAT_Type>  getValue_list () {
            return this.value_list;
        }

        public boolean isValue_listSelected () {
            return this.value_list != null;
        }

        private void setValue_list (java.util.Collection<FLOAT_Type>  value) {
            this.value_list = value;
        }

        
        public void selectValue_list (java.util.Collection<FLOAT_Type>  value) {
            this.value_list = value;
            
                    setOid_list(null);
                
                    setValue_u_list(null);
                
                    setString_list(null);
                            
        }

        
  
        
        public java.util.Collection<Poc_SelectUValueEntry>  getValue_u_list () {
            return this.value_u_list;
        }

        public boolean isValue_u_listSelected () {
            return this.value_u_list != null;
        }

        private void setValue_u_list (java.util.Collection<Poc_SelectUValueEntry>  value) {
            this.value_u_list = value;
        }

        
        public void selectValue_u_list (java.util.Collection<Poc_SelectUValueEntry>  value) {
            this.value_u_list = value;
            
                    setOid_list(null);
                
                    setValue_list(null);
                
                    setString_list(null);
                            
        }

        
  
        
        public java.util.Collection<byte[]>  getString_list () {
            return this.string_list;
        }

        public boolean isString_listSelected () {
            return this.string_list != null;
        }

        private void setString_list (java.util.Collection<byte[]>  value) {
            this.string_list = value;
        }

        
        public void selectString_list (java.util.Collection<byte[]>  value) {
            this.string_list = value;
            
                    setOid_list(null);
                
                    setValue_list(null);
                
                    setValue_u_list(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_SelectList.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            