
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_SetTimeZoneInvoke", isSet = false )
    public class Poc_SetTimeZoneInvoke implements IASN1PreparedElement {
            
        @ASN1Element ( name = "time-zone", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_UTCTimeZone time_zone = null;
                
  
        @ASN1Element ( name = "next-time-zone", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_DaylightSavingsTransition next_time_zone = null;
                
  
        
        public Poc_UTCTimeZone getTime_zone () {
            return this.time_zone;
        }

        

        public void setTime_zone (Poc_UTCTimeZone value) {
            this.time_zone = value;
        }
        
  
        
        public Poc_DaylightSavingsTransition getNext_time_zone () {
            return this.next_time_zone;
        }

        

        public void setNext_time_zone (Poc_DaylightSavingsTransition value) {
            this.next_time_zone = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_SetTimeZoneInvoke.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            