
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Poc_CtxtHelpResult", isSet = false )
    public class Poc_CtxtHelpResult implements IASN1PreparedElement {
            
        @ASN1Element ( name = "type", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private OID_Type type = null;
                
  
        @ASN1Element ( name = "op-instance-no", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private InstNumber op_instance_no = null;
                
  
        @ASN1Element ( name = "hold-time", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RelativeTime hold_time = null;
                
  
        @ASN1Element ( name = "help", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Poc_CtxtHelp help = null;
                
  
        
        public OID_Type getType () {
            return this.type;
        }

        

        public void setType (OID_Type value) {
            this.type = value;
        }
        
  
        
        public InstNumber getOp_instance_no () {
            return this.op_instance_no;
        }

        

        public void setOp_instance_no (InstNumber value) {
            this.op_instance_no = value;
        }
        
  
        
        public RelativeTime getHold_time () {
            return this.hold_time;
        }

        

        public void setHold_time (RelativeTime value) {
            this.hold_time = value;
        }
        
  
        
        public Poc_CtxtHelp getHelp () {
            return this.help;
        }

        

        public void setHelp (Poc_CtxtHelp value) {
            this.help = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_CtxtHelpResult.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            