
package ieee.poc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "Poc_SegDataNuOpt" )
    public class Poc_SegDataNuOpt implements IASN1PreparedElement {
                
            
            @ASN1SequenceOf( name = "Poc-SegDataNuOpt" , isSetOf = false)
	    private java.util.Collection<FLOAT_Type> value = null; 
    
            public Poc_SegDataNuOpt () {
            }
        
            public Poc_SegDataNuOpt ( java.util.Collection<FLOAT_Type> value ) {
                setValue(value);
            }
                        
            public void setValue(java.util.Collection<FLOAT_Type> value) {
                this.value = value;
            }
            
            public java.util.Collection<FLOAT_Type> getValue() {
                return this.value;
            }            
            
            public void initValue() {
                setValue(new java.util.LinkedList<FLOAT_Type>()); 
            }
            
            public void add(FLOAT_Type item) {
                value.add(item);
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Poc_SegDataNuOpt.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            